import { expect, test } from '@playwright/test'

async function login(page: import('@playwright/test').Page, username: string, password: string) {
  await page.goto('/')
  await page.getByLabel('帳號').fill(username)
  await page.getByLabel('密碼').fill(password)
  await page.getByRole('button', { name: '登入', exact: true }).click()
}

test('viewer sees L1 and cannot open L2 or L3', async ({ page }) => {
  await login(page, 'viewer', 'viewer')
  await expect(page.getByRole('heading', { name: '供應鏈風險' })).toBeVisible()
  const candidate = page.locator('.overview-stream--intel .rows > li').filter({ hasText: 'E2E 港口運輸中斷' })
  await expect(candidate).toContainText('E2E 測試來源')
  await expect(candidate.getByRole('link', { name: '閱讀原文' })).toHaveAttribute('href', 'https://example.invalid/e2e-port')
  await page.getByRole('button', { name: '供應風險地圖' }).click()
  await expect(page.getByRole('heading', { name: '供應風險地圖' })).toBeVisible()
  await expect(page.getByRole('group', { name: '供應據點經緯度圖' })).toBeVisible()
  await page.getByRole('button', { name: '風險事件' }).click()
  await expect(page.getByRole('heading', { name: '風險事件' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '登錄事件' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'What-if 分析' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '情報審查' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'L2 替代採購提案' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'L3 人工核准' })).toHaveCount(0)
  await page.getByRole('button', { name: '決策紀錄' }).click()
  await page.locator('.rows > li').filter({ hasText: 'E2E 港口延誤時哪些採購單受影響？' }).getByRole('button', { name: '查看證據' }).click()
  await expect(page.getByRole('button', { name: '檢視當時資料' })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: '供應鏈風險' })).toBeVisible()
})

test('planner reviews sourced news before it becomes a risk event', async ({ page }) => {
  await login(page, 'planner', 'planner')
  await page.getByRole('button', { name: '情報審查' }).click()
  await expect(page.getByRole('heading', { name: '供應鏈情報審查' })).toBeVisible()
  const story = page.locator('.news-card').filter({ hasText: 'E2E 港口運輸中斷' })
  await expect(story).toBeVisible()
  await expect(story).toContainText('E2E 測試來源')
  await expect(story.getByRole('link', { name: '閱讀原文' })).toHaveAttribute('href', 'https://example.invalid/e2e-port')
  await story.getByRole('button', { name: '確認並建立事件' }).click()
  await expect(page.getByRole('status')).toContainText('新聞已確認並建立風險事件')
  await page.getByLabel('檢視狀態').selectOption('confirmed')
  await expect(page.locator('.news-card').filter({ hasText: 'E2E 港口運輸中斷' })).toContainText('已連結風險事件')
  await page.getByRole('button', { name: '風險事件' }).click()
  const event = page.locator('section.panel > ul.rows > li').filter({ hasText: 'E2E 港口運輸中斷' })
  await expect(event).toContainText('E2E 測試來源')
  await expect(event.getByRole('link', { name: '閱讀原文' })).toHaveAttribute('href', 'https://example.invalid/e2e-port')
  await event.getByRole('button', { name: '撤銷' }).click()
  await event.getByLabel('撤銷原因').fill('E2E 覆核後撤銷此事件')
  await event.getByRole('button', { name: '確認撤銷' }).click()
  await expect(event).toHaveCount(0)
  await page.locator('.retracted-events').locator('summary').click()
  await expect(page.locator('.retracted-events')).toContainText('E2E 覆核後撤銷此事件')
  await page.getByRole('button', { name: '情報審查' }).click()
  await page.getByLabel('檢視狀態').selectOption('confirmed')
  await expect(page.locator('.news-card').filter({ hasText: 'E2E 港口運輸中斷' })).toContainText('事件已撤銷')
})

test('planner can inspect the private ERP evidence behind a What-if decision', async ({ page }) => {
  await login(page, 'planner', 'planner')
  await page.getByRole('button', { name: '決策紀錄' }).click()
  await page.locator('.rows > li').filter({ hasText: 'E2E 港口延誤時哪些採購單受影響？' }).getByRole('button', { name: '查看證據' }).click()
  await page.getByRole('button', { name: '檢視當時資料' }).click()
  await expect(page.getByText('擷取時間：', { exact: false })).toBeVisible()
  await page.locator('.erp-source').filter({ hasText: '未結採購單' }).locator('summary').click()
  await expect(page.locator('.erp-source').filter({ hasText: '未結採購單' })).toContainText('E2E-DELAYED')
  await page.getByRole('button', { name: '採納建議' }).click()
  await expect(page.locator('.decision-detail')).toContainText('adopted')
  await page.getByLabel('實際採取動作').fill('E2E 已通知採購規劃員')
  await page.getByLabel('結果依據').fill('E2E 已覆核採購單與庫存')
  await page.getByRole('button', { name: '儲存回饋' }).click()
  await expect(page.locator('.decision-detail')).toContainText('E2E 已覆核採購單與庫存')
})

test('planner records a risk event in the Vue workspace', async ({ page }) => {
  await login(page, 'planner', 'planner')
  await page.getByRole('button', { name: '風險事件' }).click()
  await page.getByLabel('事件類型').selectOption('交通')
  await page.getByLabel('國家').fill('台灣')
  await page.getByLabel('地區').fill('台北')
  await page.getByLabel('預估影響天數').fill('3')
  await page.getByLabel('描述').fill('E2E 驗證運輸延誤')
  await page.getByRole('button', { name: '儲存事件' }).click()
  await expect(page.getByText('E2E 驗證運輸延誤')).toBeVisible()
  await expect(page.getByRole('button', { name: 'What-if 分析' })).toBeVisible()
})

test('planner sees the proposal workspace', async ({ page }) => {
  await login(page, 'planner', 'planner')
  await page.getByRole('button', { name: 'L2 替代採購提案' }).click()
  await expect(page.getByRole('heading', { name: '受影響採購單' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'L3 人工核准' })).toHaveCount(0)
})

test('approver sees the review queue', async ({ page }) => {
  await login(page, 'approver', 'approver')
  await page.getByRole('button', { name: 'L3 人工核准' }).click()
  await expect(page.getByRole('heading', { name: '待審核採購提案' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'L2 替代採購提案' })).toHaveCount(0)
})

test('planner submits and a different approver completes one ERP effect', async ({ page }) => {
  await login(page, 'planner', 'planner')
  await page.getByRole('button', { name: 'L2 替代採購提案' }).click()
  const order = page.locator('.rows > li').filter({ hasText: 'E2E-DELAYED' })
  await expect(order).toBeVisible()
  await order.getByRole('button', { name: '查看備援來源' }).click()
  await expect(page.getByLabel('備援供應商')).toBeVisible()
  await page.getByRole('button', { name: '送交 L3 核准' }).click()
  await expect(page.getByRole('status')).toContainText('已送交 L3 審核')

  await page.getByRole('button', { name: '登出' }).click()
  await login(page, 'approver', 'approver')
  await page.getByRole('button', { name: 'L3 人工核准' }).click()
  const approval = page.locator('.rows > li').filter({ hasText: 'proposal:create-po:' })
  await expect(approval).toBeVisible()
  await approval.getByRole('button', { name: '審查' }).click()
  await expect(page.getByRole('heading', { name: '提案證據' })).toBeVisible()
  await page.getByRole('button', { name: '核准並執行' }).click()
  await expect(page.getByText('執行完成')).toBeVisible()
  await expect(page.getByText('收據：', { exact: false })).toBeVisible()
  await expect(page.getByText('目前沒有待審核的替代採購提案。')).toBeVisible()
})

test('approver rejects a separate proposal without an ERP effect', async ({ page }) => {
  await login(page, 'planner', 'planner')
  await page.getByRole('button', { name: 'L2 替代採購提案' }).click()
  const order = page.locator('.rows > li').filter({ hasText: 'E2E-REJECTED' })
  await expect(order).toBeVisible()
  await order.getByRole('button', { name: '查看備援來源' }).click()
  await page.getByRole('button', { name: '送交 L3 核准' }).click()
  await expect(page.getByRole('status')).toContainText('已送交 L3 審核')

  await page.getByRole('button', { name: '登出' }).click()
  await login(page, 'approver', 'approver')
  await page.getByRole('button', { name: 'L3 人工核准' }).click()
  const approval = page.locator('.rows > li').filter({ hasText: 'proposal:create-po:' })
  await expect(approval).toBeVisible()
  await approval.getByRole('button', { name: '審查' }).click()
  await expect(page.getByRole('heading', { name: '提案證據' })).toBeVisible()
  await page.getByLabel('拒絕原因').fill('E2E 備援價格尚待確認')
  await page.getByRole('button', { name: '拒絕', exact: true }).click()
  await expect(page.getByRole('heading', { name: '最近一次審核歷程' })).toBeVisible()
  await expect(page.getByText('已拒絕')).toBeVisible()
  await expect(page.getByText('執行完成')).toHaveCount(0)
  await expect(page.getByText('目前沒有待審核的替代採購提案。')).toBeVisible()
})
